### ISSUE TITLE
make withStdout method

### ISSUE THREAD

**Issue by levBagryansky** [yegor256/jaxec#39]
Now if exit code is not 0, execUsafe throws Exception without stdout, but it could.

**Comment by yegor256** [comment]
@levBagryansky it may be tricky, since some stdout may be very very large (megabytes of data). However, we can try to think about some solution.

**Comment by levBagryansky** [comment]
@yegor256 I think we can create an `ExceptionWithLog` with `String log()` method. Then user could catch it and get the `stdout`.

**Comment by c71n93** [comment]
@yegor256 @levBagryansky I think that non-zero exit code from subprocess is not an exception at all. For example user may want just to execute subprocess and check it's exit code (even if it is non zero). However now user unable to check exit code. I would like to return pair that contains stdout and exit code (or some "Result" object) without throwing exception.

**Comment by levBagryansky** [comment]
@yegor256 What do you think

**Comment by yegor256** [comment]
@levBagryansky I believe, the best way would be to enable forwarding of stdout to a stream:

```
baos = new ByteArrayOutputStream();
String stdout = new Jaxec("ls", "-al")
  .with("/tmp")
  .withStdout(baos)
  .exec();
```

This way, the `stdout` will contain the result _and_ the `baos` stream will receive the data too.

**Comment by levBagryansky** [comment]
@yegor256 check

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.0`
